# Generated by Django 4.2.10 on 2025-05-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("selection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="current_stage",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="selection.selectionstage",
            ),
        ),
    ]
