# Generated by Django 4.2.10 on 2025-05-27 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superusuario'), ('ADMIN', 'Administrador'), ('HR_MANAGER', 'Personal de RRHH'), ('SUPERVISOR', 'Supervisor/Gerente'), ('EMPLOYEE', 'Empleado'), ('USER', 'Usuario Básico')], default='USER', max_length=20, verbose_name='Rol'),
        ),
    ]
