# Generated by Django 4.2.10 on 2025-05-27 17:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('INDEFINITE', 'Indefinido'), ('FIXED_TERM', 'Término Fijo'), ('TEMPORARY', 'Temporal'), ('INTERNSHIP', 'Pasantía')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('COP', 'Peso Colombiano'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], default='COP', max_length=3)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('work_schedule', models.CharField(choices=[('FULL_TIME', 'Tiempo Completo'), ('PART_TIME', 'Tiempo Parcial'), ('FLEX_TIME', 'Tiempo Flexible'), ('SHIFT_WORK', 'Trabajo por Turnos')], default='FULL_TIME', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='affiliation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period__start_date', 'contract__employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.CharField(choices=[('EARNING', 'Devengo'), ('DEDUCTION', 'Deducción')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_percentage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('BIWEEKLY', 'Quincenal'), ('MONTHLY', 'Mensual'), ('WEEKLY', 'Semanal'), ('CUSTOM', 'Personalizado')], default='MONTHLY', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payrollentry')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollitem')),
            ],
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollentry',
            unique_together={('contract', 'period')},
        ),
    ]
