# Generated by Django 4.2.10 on 2025-05-27 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selection', '0001_initial'),
        ('core', '0001_initial'),
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='selection.candidate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliationtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_types', to='core.company'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_affiliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='affiliation.employee'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliation.provider'),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('name', 'affiliation_type')},
        ),
        migrations.AlterUniqueTogether(
            name='affiliationtype',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('employee', 'provider', 'start_date')},
        ),
    ]
