# Generated by Django 4.2.10 on 2025-05-29 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to=settings.AUTH_USER_MODEL),
        ),
    ]
